export const images = {
  profileBackground: require("./profile-background.png"),
  profileFace: require("./profile-face.png"),
  chair: require("./chair.png"),
  chair2: require("./chair-2.png"),
  light: require("./light.png"),
  camera: require("./camera.png"),
  folio: require("./folio.png"),
  bottle1: require("./bottle-1.png"),
  bottle2: require("./bottle-2.png"),
  bottle3: require("./bottle-3.png"),
  bottle4: require("./bottle-4.png"),
  bowl: require("./bowl.png"),
  clock: require("./clock.png"),
  curator1: require("./curator-1.png"),
  curator2: require("./curator-2.png"),
  flowerPot: require("./flower-pot.png"),
  homeHero: require("./home-hero.png"),
  stoneMonolith: require("./stone-monolith.png"),
  p1: require("./p-1.png"),
  p2: require("./p-2.png"),
  p3: require("./p-3.png"),
  p4: require("./p-4.png"),
  icon: require("./icon.png"),
};
